name: Unpack boot/rec

on:
  workflow_dispatch:
    inputs:
      IMG_URL:    
        description: 'IMG_URL'
        required: true
        default: ''

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-22.04
    
    steps:
    - name: Check Out
      uses: actions/checkout@main
      
    - name: Prepare the environment
      run: |
        sudo apt update
        sudo apt -y install wget abootimg
        mkdir unpack
        mkdir unpack/initrd
      
    - name: Download boot or recovery img
      run: |
        aria2c "${{ github.event.inputs.IMG_URL }}"
        ls
      
    - name: Start unpack
      run: |
        abootimg -x new_boot.img unpack
        abootimg -unpack -initrd unpack/initrd.img unpack/initrd
    - name: ZIP unpack files
      run: |
        zip -r unpack.zip ./unpack
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./unpack.zip
        name: Unpack Files-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: Files from boot/rec
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
